server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:

            - id: agendamento-auth
              uri: ${AGENDAMENTO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/auth/**

            - id: agendamento-usuarios
              uri: ${AGENDAMENTO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/usuarios/**

            - id: agendamento-consultas
              uri: ${AGENDAMENTO_SERVICE_URL:http://localhost:8081}
              predicates:
                - Path=/api/v1/consultas/**

            - id: historico-graphql
              uri: ${HISTORICO_SERVICE_URL:http://localhost:8082}
              predicates:
                - Path=/graphql

management:
  endpoints:
    web:
      exposure:
        include: health,info,gateway

  endpoint:
    gateway:
      access: read-only