spring:
  application:
    name: agendamento-service

  datasource:
    url: jdbc:postgresql://localhost:5432/healthcare_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: create-drop
    open-in-view: false

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: ${JWT_SECRET:bXlTdXBlclNlY3JldEtleUZvckpXVDEyMzQ1Njc4OTA=}
  expiration: ${JWT_EXPIRATION:3600000}

server:
  port: 8081

app:
  messaging:
    exchange: consultas.exchange
    routing-key:
      criada: consulta.criada
      atualizada: consulta.atualizada

